// app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Admin-Mihir",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
